#!/usr/bin/env bash
# Installing nginx on ubuntu server 20.04

apt update &&
apt -y install nginx
# Firewall port 80
ufw allow 'Nginx HTTP'
# Index file and start
echo "Hello World!" > /var/www/html/index.html &&
/etc/init.d/nginx start
