#!/usr/bin/env bash
# Install the load balanecer

apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend asmamaw-alx-frontend
	bind *:80
	mode http
	default_backend back
backend asmamaw-alx-backend
    balance roundrobin
    server 1271-web-01 35.227.42.183:80 check
    server 1271-web-02 34.74.166.35:80 check
EOF
service haproxy restart
